<<<<<<< Updated upstream
theme: minimal
=======
markdown: kramdown
highlighter: rouge

repository: blank_repo_url
help_url: blank_help_url

timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com

twitter:
  username: jekyllrb

logo: /img/logo-2x.png

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md
>>>>>>> Stashed changes
